const purchaseData = [
    {
        id:1,
        month:"Apr",
        purchase:200000
    },
    {
        id:2,
        month:"May",
        purchase:200000
    },
    {
        id:3,
        month:"Jun",
        purchase:200000
    },
    {
        id:4,
        month:"jul",
        purchase:200000
    },
    {
        id:5,
        month:"Aug",
        purchase:200000
    },
    {
        id:6,
        month:"Sep",
        purchase:2010000
    },
    {
        id:7,
        month:"Oct",
        purchase:200000
    },
    {
        id:8,
        month:"Nov",
        purchase:2850000
    },
    {
        id:9,
        month:"Dec",
        purchase:200000
    },
    {
        id:10,
        month:"Jan",
        purchase:100000
    },
    {
        id:11,
        month:"Feb",
        purchase:2050000
    },
    {
        id:12,
        month:"Mar",
        purchase:900000
    },

]
export default purchaseData